spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/minedb?characterEncoding=UTF-8&serverTimezone=UTC

    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

  servlet:
    multipart:
      enabled: true
      location: C:\Users\minhye\mine-web\image_save
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 1MB


server:
  port: 8080

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      sql: debug